### ISSUE TITLE
Create Wireframes for Most Important Views

### ISSUE THREAD

**Issue by Carmer** [TheKaterTot/education_gives#1]
Think about what you think the workflow should be on the site. Which of those views is most important?
      In addition to the home page wireframe, create wireframes the page immediately following your Log In and the next most important page for your application.
      Examples might be: A users' profile page, a product page, an admin dashboard etc...

**Comment by AELSchauer** [comment]
http://mashable.com/2010/07/15/wireframing-tools/#5LzPpfuXxZqs
