### ISSUE TITLE
Navigate through the website and make sure all is accessible by link without typing in browser

### ISSUE THREAD

**Issue by pixapi** [TheKaterTot/education_gives#115]

**Comment by AELSchauer** [comment]
FEATURE FAILURES
* Retired donations still appear on donation index page
* Admin donation index image not rendering properly & causing error
* Unable to view an individual order page (add authorization)
* Add user's first name, last name, and email to the order show table.
* Order show page has missing total
* Order show page is showing end date if status is "Ordered"
* Order show page date should include time
* Order index page has no total and is in the wrong column with the order status
* Remove ability to edit price from edit donation page
* Change button to say "Login or Create Account to Checkout"
* Navbar appears on 404 category page


STYLING HIGH PRIORITY
* Add navbar link to view items by category (make a donation dropdown)
* Add error messsages to new and edit donation pages
* image for custom 404 page is broken (e.g. go to admin/dashboard as unautheticated user)
* image for 404 image too big
* 404 page should include a link to the donations or home page (image should be link?)
* When I log out, I shouldn't lose all the data in my cart.
* Admin dashboard table is all sorts of fucked up


MEDIUM PRIORITY
* Fix image size on donation show page
* Fix image size on cart
* Fix table spacing on cart
* Move "view all donations" link on admin dashboard to navbar
* Order show page has extra date td
* Add table styling on new & edit donation pages & use display_name for category in dropdown
* Remove "image_path" from donation table
* Add link to create new donation on admin/donations
* Add styling to admin donation show page
* Remove "all orders" heading from admin dashboard
* Add consistent styling for "mark as cancelled" button on admin dashboard
* Update so displays as currency


LOW PRIORITY
* How do I remove an image from a donation in app?
* How do I mark a donation as inactive in app?
* Switch cancelled and completed on subtotals page
