### ISSUE TITLE
13- Authentication/Authorization (logged user)

### ISSUE THREAD

**Issue by pixapi** [TheKaterTot/education_gives#47]
title: Authenticated users security
    body: >
      Background: An authenticated user 
      As an Authenticated User
      I cannot view another user's private data (current or past orders, etc)
      I cannot view the administrator screens or use admin functionality
      I cannot make myself an admin

**Comment by edilenedacruz** [comment]
We asked the teachers if there's a way to make this test "I cannot make myself an admin"
